apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- resources/namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.1/manifests/install.yaml
